/**
 * WU7A — canonical NFL betting-splits slate builder.
 *
 * The betting-splits domain does not own an NFL schedule source. The repo's
 * existing nflverse-derived artifact `public/data/nfl/<season>/games.json`
 * (generated by `scripts/generate-nfl-schedules-results.mjs`) is the single
 * canonical `NflGameRecord[]` source. This module loads that document and
 * narrows it to one `(season, week, seasonType)` slate so it can be handed
 * straight to {@link runBettingSplitsCollection} — no second schedule source,
 * no mandatory intermediate file.
 *
 * SportsDataIO is never consulted here: provider identity must never define a
 * canonical game.
 */

import type { NflGameRecord } from "../nfl/standings";
import type { SportsDataIoSeasonType } from "./providers/sportsDataIoClient";

/** nflverse `seasonType` tokens grouped by the provider season-type family. */
const SEASON_TYPE_FAMILIES: Record<SportsDataIoSeasonType, readonly string[]> = {
  PRE: ["PRE"],
  REG: ["REG"],
  POST: ["WC", "DIV", "CON", "SB", "POST"],
};

export type CanonicalNflSlate = {
  season: number;
  week: number;
  seasonType: SportsDataIoSeasonType;
  /** Absolute or repo-relative description of where the schedule came from. */
  source: string;
  /** Games in the canonical document for this season (all weeks). */
  seasonGameCount: number;
  /** Games retained for this slate. */
  games: NflGameRecord[];
};

export type LoadCanonicalNflSlateInput = {
  season: number;
  week: number;
  seasonType: SportsDataIoSeasonType;
  /** Parsed contents of `public/data/nfl/<season>/games.json`. */
  gamesDocument: unknown;
  /** Human-readable provenance for logs/reports. */
  source?: string;
};

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null;
}

/**
 * Narrow the canonical nflverse games document to a single slate.
 *
 * Throws when the document shape is wrong or the slate is empty — the refresh
 * pipeline must fail fast rather than call the provider for a phantom week.
 */
export function loadCanonicalNflSlate(
  input: LoadCanonicalNflSlateInput,
): CanonicalNflSlate {
  const { season, week, seasonType } = input;
  if (!Number.isInteger(season) || season < 2000) {
    throw new Error(`season must be a year >= 2000; received ${season}`);
  }
  if (!Number.isInteger(week) || week <= 0) {
    throw new Error(`week must be a positive integer; received ${week}`);
  }

  if (!isRecord(input.gamesDocument) || !Array.isArray(input.gamesDocument.games)) {
    throw new Error(
      "Canonical NFL schedule document must be { games: NflGameRecord[] } " +
        "(the shape of public/data/nfl/<season>/games.json).",
    );
  }

  const source = input.source ?? `public/data/nfl/${season}/games.json`;
  const seasonGames = (input.gamesDocument.games as NflGameRecord[]).filter(
    (game) => game.season === season,
  );

  const family = SEASON_TYPE_FAMILIES[seasonType];
  const games = seasonGames
    .filter((game) => game.week === week && family.includes(game.seasonType))
    .slice()
    .sort((left, right) => left.gameId.localeCompare(right.gameId));

  if (games.length === 0) {
    throw new Error(
      `Canonical NFL schedule ${source} has no ${seasonType} games for ` +
        `season ${season} week ${week}. Refusing to run a provider request ` +
        "against an empty slate.",
    );
  }

  return {
    season,
    week,
    seasonType,
    source,
    seasonGameCount: seasonGames.length,
    games,
  };
}

export { SEASON_TYPE_FAMILIES };
