import type { DailyProfile, NumerologyScoreBreakdown, NumerologySignal } from "@/types/mlbNumerology";

export type PlayerIdentity = { birthDate?: string | null; jerseyNumber?: number | null };
export type AuditablePlayer = { playerName: string; jerseyNumber?: number | null; battingOrder?: number | null; numerologyScore: number };

type Reduced = { original: number; compound: number; master: number | null; root: number };
const MASTER = new Set([11, 22, 33]);
const FAMILY = [[1,4,7],[2,5,8],[3,6,9]];
const PYTH: Record<string,number> = {a:1,j:1,s:1,b:2,k:2,t:2,c:3,l:3,u:3,d:4,m:4,v:4,e:5,n:5,w:5,f:6,o:6,x:6,g:7,p:7,y:7,h:8,q:8,z:8,i:9,r:9};
const DEFAULTS: Record<string,number> = {personalDayExactMaster:20,personalDayRoot:14,jerseyExactMaster:16,jerseyRoot:12,battingOrderExactRoot:12,lifePathExactMaster:14,lifePathRoot:10,birthDayExactCompound:10,birthDayRoot:7,ageExactCompound:9,ageRoot:5,expressionRoot:6,primaryFamilyMatch:3,calendarDayExactCompound:8,calendarDayRoot:5,secondaryFamilyMatch:2,repeatedDateDigit:2,countercurrentHighField:6,countercurrentMultiple:3,convergenceMaxBonus:8};
const sum = (n:number) => String(Math.abs(Math.round(n))).split("").reduce((a,d)=>a+Number(d),0);
function reduce(n:number): Reduced { const original=Math.abs(Math.round(n)); if(original<10)return{original,compound:original,master:null,root:original}; if(MASTER.has(original))return{original,compound:original,master:original,root:sum(original)}; const compound=sum(original); if(MASTER.has(compound))return{original,compound,master:compound,root:sum(compound)}; let root=compound; while(root>9)root=sum(root); return{original,compound,master:null,root}; }
const fmt=(v:Reduced|null)=>v?(v.original===v.root?String(v.root):`${v.original}/${v.root}`):null;
const norm=(s:string)=>s.normalize("NFKD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/[^a-z]/g,"");
const expression=(name:string)=>reduce([...norm(name)].reduce((a,c)=>a+(PYTH[c]??0),0));
const lifePath=(date:string)=>reduce([...date.replace(/\D/g,"")].reduce((a,d)=>a+Number(d),0));
function ageOn(birth:string,slate:string){const[by,bm,bd]=birth.split("-").map(Number);const[sy,sm,sd]=slate.split("-").map(Number);return sy-by-(sm<bm||(sm===bm&&sd<bd)?1:0);}
function family(root:number){return FAMILY.find((f)=>f.includes(root))??[];}

export function calculateNumerologyScoreBreakdown(player:AuditablePlayer,identity:PlayerIdentity|null,daily:DailyProfile,slateDate:string,configured?:Record<string,number>):NumerologyScoreBreakdown{
 const W={...DEFAULTS,...(configured??{})}; const[,month,day]=slateDate.split("-").map(Number); const birth=identity?.birthDate??null; const jerseyNo=player.jerseyNumber??identity?.jerseyNumber??null; const batting=player.battingOrder??null; const jersey=jerseyNo==null?null:reduce(jerseyNo); const age=birth?ageOn(birth,slateDate):null; const ageR=age==null?null:reduce(age); const life=birth?lifePath(birth):null; const birthDay=birth?reduce(Number(birth.slice(-2))):null; const py=birth?reduce(Number(birth.slice(5,7))+Number(birth.slice(-2))+daily.universalYear):null; const pm=py?reduce(py.root+month):null; const personal=pm?reduce(pm.root+day):null; const expr=expression(player.playerName); const signals:NumerologySignal[]=[]; const used=new Set<string>(); const add=(field:string,label:string,type:NumerologySignal["type"],points:number,description:string,key:string)=>{if(!used.has(key)){used.add(key);signals.push({field,label,type,points,description});}}; const target=daily.universalDayRawSum; const root=daily.universalDayRoot; const counter=daily.countercurrent; const primary=daily.primaryFamily??family(root); const secondary=daily.secondaryFamily??[];
 const scoreReduced=(field:string,title:string,v:Reduced|null,exactWeight:number,rootWeight:number)=>{if(!v)return;if(daily.universalDayMaster!=null&&(v.original===daily.universalDayMaster||v.compound===daily.universalDayMaster||v.master===daily.universalDayMaster))add(field,`${title} ${fmt(v)} — Master Match`,"primary_exact_master",exactWeight,`${title} matches the Universal Day master.`,`${field}:master`);else if(v.original===target||v.compound===target)add(field,`${title} ${fmt(v)} — Exact Primary`,"primary_exact_root",Math.max(1,exactWeight-2),`${title} matches Universal Day ${target}.`,`${field}:exact`);else if(v.root===root)add(field,`${title} ${fmt(v)} — Root Match`,"primary_root",rootWeight,`${title} reduces to today's root ${root}.`,`${field}:root`);else if(v.root===counter)add(field,`${title} ${fmt(v)} — Countercurrent`,"countercurrent",-Math.round(W.countercurrentHighField*(field==="lifePath"?.5:1)),`${title} reduces to countercurrent ${counter}.`,`${field}:counter`);};
 scoreReduced("personalDay","Personal Day",personal,W.personalDayExactMaster,W.personalDayRoot); scoreReduced("lifePath","Life Path",life,W.lifePathExactMaster,W.lifePathRoot); scoreReduced("age","Age",ageR,W.ageExactCompound,W.ageRoot);
 if(jersey){if(jersey.original===daily.calendarDayCompound)add("jersey",`Jersey ${jersey.original} — Calendar Day Exact`,"secondary_exact",W.calendarDayExactCompound,"Jersey equals the calendar day.","jersey:calendar");else scoreReduced("jersey","Jersey",jersey,W.jerseyExactMaster,W.jerseyRoot); if(!used.has("jersey:master")&&!used.has("jersey:exact")&&!used.has("jersey:root")&&!used.has("jersey:counter")&&!used.has("jersey:calendar")){if(primary.includes(jersey.root))add("jersey",`Jersey root ${jersey.root} — Primary Family`,"family_support",W.primaryFamilyMatch,"Jersey root belongs to the primary family.","jersey:family");else if(secondary.includes(jersey.root))add("jersey",`Jersey root ${jersey.root} — Secondary Family`,"family_support",W.secondaryFamilyMatch,"Jersey root belongs to the secondary family.","jersey:family");}}
 if(birthDay){if(birthDay.original===daily.calendarDayCompound)add("birthDay",`Birth Day ${birthDay.original} — Calendar Day Exact`,"secondary_exact",W.birthDayExactCompound,"Birth day equals the calendar day.","birth:calendar");else if(birthDay.root===root)add("birthDay",`Birth Day ${fmt(birthDay)} — Root Match`,"primary_root",W.birthDayRoot,`Birth day reduces to ${root}.`,"birth:root");}
 if(batting!=null){if(batting===root)add("battingOrder",`Batting ${batting} — Exact Root Match`,"primary_exact_root",W.battingOrderExactRoot,"Batting order equals today's root.","batting:root");else if(primary.includes(batting))add("battingOrder",`Batting ${batting} — Primary Family`,"family_support",W.primaryFamilyMatch,"Batting order belongs to the primary family.","batting:family");else if(secondary.includes(batting))add("battingOrder",`Batting ${batting} — Secondary Family`,"family_support",W.secondaryFamilyMatch,"Batting order belongs to the secondary family.","batting:family");}
 if(expr.root===root)add("expression",`Expression ${fmt(expr)} — Root Match`,"name_resonance",W.expressionRoot,"Name Expression matches today's root.","expression:root");
 for(const repeated of daily.repeatedDigits??[]){if(repeated.reinforces==="primary"&&((jersey?.root===repeated.digit)||(jersey?.original===repeated.digit)||batting===repeated.digit))add("repeatedDigit",`Date digit ${repeated.digit} (×${repeated.count}) — Contextual Echo`,"contextual_echo",W.repeatedDateDigit,"Repeated date digit reinforces an existing field.",`repeat:${repeated.digit}`);}
 const counters=signals.filter((s)=>s.type==="countercurrent"); if(counters.length>1)signals.push({field:"multiCountercurrent",label:`${counters.length} independent countercurrents`,type:"countercurrent",points:-(W.countercurrentMultiple*(counters.length-1)),description:"Multiple countercurrents compound."}); const positiveTotal=signals.filter((s)=>s.points>0).reduce((a,s)=>a+s.points,0); const countercurrentTotal=Math.abs(signals.filter((s)=>s.points<0).reduce((a,s)=>a+s.points,0)); const independent=new Set(signals.filter((s)=>s.points>0&&!['family_support','contextual_echo'].includes(s.type)).map((s)=>s.field)); const convergenceBonus=independent.size>=4?W.convergenceMaxBonus:independent.size>=3?Math.round(W.convergenceMaxBonus*.5):0; const missingData=[!birth?"birthDate":null,jerseyNo==null?"jersey":null].filter(Boolean) as string[]; let ceiling=W.jerseyExactMaster+W.expressionRoot+W.convergenceMaxBonus;if(birth)ceiling+=W.personalDayExactMaster+W.lifePathExactMaster+W.birthDayExactCompound+W.ageExactCompound;if(batting!=null)ceiling+=W.battingOrderExactRoot; const normCeiling=Math.max(60,ceiling); const rawNumerology=Math.max(0,positiveTotal-countercurrentTotal+convergenceBonus); const calculatedScore=Math.min(100,Math.round(rawNumerology/normCeiling*100)); return{signals,positiveTotal,countercurrentTotal,convergenceBonus,rawNumerology,normCeiling,calculatedScore,reportedScore:player.numerologyScore,scoreVerified:calculatedScore===Number(player.numerologyScore),profile:{personalDay:fmt(personal),jersey:jersey?`#${jerseyNo} (${fmt(jersey)})`:null,battingOrder:batting==null?null:String(batting),lifePath:fmt(life),birthDay:fmt(birthDay),age:ageR?`${age} (${fmt(ageR)})`:null,expression:fmt(expr)},missingData};
}
