/**
 * Types for `public/data/nfl/<season>/yardage-history.json`, generated by
 * `scripts/generate-nfl-yardage-history.mjs` (see that script's header for
 * the full source map and leakage-safety rules). Presentation/history only
 * -- consumed by the Yardage Props Review Last-10 tables, never by any
 * model input.
 */
import type { NflProjectionMarket } from "./projectionOutput";

export type NflYardageGameResult = "W" | "L" | "T" | null;

export type NflYardageHistoryGameScore = {
  result: NflYardageGameResult;
  teamScore: number | null;
  oppScore: number | null;
} | null;

export type NflYardagePassingStatBlock = { completions: number; attempts: number; passingTds: number; interceptions: number };
export type NflYardageRushingStatBlock = { rushAttempts: number; rushTds: number };
export type NflYardageReceivingStatBlock = { targets: number; receptions: number; recTds: number };
export type NflYardageStatBlock = NflYardagePassingStatBlock | NflYardageRushingStatBlock | NflYardageReceivingStatBlock;

export type NflYardagePlayerHistoryGame = {
  gameId: string | null;
  season: number;
  week: number;
  dateUtc: string | null;
  opponentAbbr: string | null;
  homeAway: "home" | "away" | null;
  oppDefRank: number | null;
  oppYdsAllowAvg: number | null;
  stat: NflYardageStatBlock;
  actualYards: number;
  gameScore: NflYardageHistoryGameScore;
  vegasLine: number | null;
};

export type NflYardagePlayerHistory = {
  playerId: string;
  playerName: string;
  market: NflProjectionMarket;
  position: string;
  games: NflYardagePlayerHistoryGame[];
};

export type NflYardageOpponentHistoryGame = {
  gameId: string | null;
  season: number;
  week: number;
  dateUtc: string | null;
  opponentPlayerId: string;
  opponentPlayerName: string;
  homeAway: "home" | "away" | null;
  oppOffRank: number | null;
  oppPlayerYpg: number | null;
  stat: NflYardageStatBlock;
  yardsAllowed: number;
  gameScore: NflYardageHistoryGameScore;
  vegasLine: number | null;
};

export type NflYardageOpponentHistory = {
  team: string;
  market: NflProjectionMarket;
  position: string;
  games: NflYardageOpponentHistoryGame[];
};

export type NflYardageHistoryArtifact = {
  _meta: { generatedAt: string; source: string; season: number | null; week: number | null; notes: string[] };
  schemaVersion: string;
  season: number;
  week: number;
  players: Record<string, NflYardagePlayerHistory>;
  teamDefense: Record<string, NflYardageOpponentHistory>;
};

export function playerHistoryKey(playerId: string, market: NflProjectionMarket): string {
  return `${playerId}:${market}`;
}

export function opponentHistoryKey(opponentAbbr: string, market: NflProjectionMarket, position: string): string {
  return `${opponentAbbr}:${market}:${position}`;
}
