/**
 * Types for `public/data/nfl/<season>/yardage-history.json`, generated by
 * `scripts/generate-nfl-yardage-history.mjs` (see that script's header for
 * the full source map and leakage-safety rules). Presentation/history only
 * -- consumed by the Yardage Props Review Last-10 tables, never by any
 * model input.
 */
import type { NflProjectionMarket } from "./projectionOutput";
import type { IndividualYardageHistoryContext } from "@/lib/nfl/history/contracts";

export type NflYardageGameResult = "W" | "L" | "T" | null;

export type NflYardageHistoryGameScore = {
  result: NflYardageGameResult;
  teamScore: number | null;
  oppScore: number | null;
} | null;

export type NflYardagePassingStatBlock = { completions: number; attempts: number; passingTds: number; interceptions: number };
export type NflYardageRushingStatBlock = { rushAttempts: number; rushTds: number };
export type NflYardageReceivingStatBlock = { targets: number; receptions: number; recTds: number };
export type NflYardageStatBlock = NflYardagePassingStatBlock | NflYardageRushingStatBlock | NflYardageReceivingStatBlock;

export type NflYardagePlayerHistoryGame = {
  gameId: string | null;
  season: number;
  week: number;
  dateUtc: string | null;
  opponentAbbr: string | null;
  homeAway: "home" | "away" | null;
  oppDefRank: number | null;
  /** Teams with a resolvable pregame rank at this game's cutoff -- not always 32; null whenever oppDefRank is null. */
  oppDefRankPoolSize: number | null;
  oppYdsAllowAvg: number | null;
  stat: NflYardageStatBlock;
  actualYards: number;
  /**
   * Full PPR fantasy points for this game, taken verbatim from nflverse
   * `stats_player_week.fantasy_points_ppr` (never recomputed). Additive and
   * QB/passing-only -- present on `market: "passing"` game rows, absent on
   * rushing/receiving rows (older artifacts predate the field entirely, so
   * consumers must tolerate `undefined`). `null` when the source row had no
   * value.
   */
  fantasyPointsPpr?: number | null;
  gameScore: NflYardageHistoryGameScore;
  vegasLine: number | null;
};

export type NflYardagePlayerHistory = {
  playerId: string;
  playerName: string;
  market: NflProjectionMarket;
  position: string;
  games: NflYardagePlayerHistoryGame[];
};

export type NflYardageOpponentHistoryGame = {
  gameId: string | null;
  season: number;
  week: number;
  dateUtc: string | null;
  opponentPlayerId: string;
  opponentPlayerName: string;
  homeAway: "home" | "away" | null;
  oppOffRank: number | null;
  /** Teams with a resolvable pregame rank at this game's cutoff -- not always 32; null whenever oppOffRank is null. */
  oppOffRankPoolSize: number | null;
  oppPlayerYpg: number | null;
  stat: NflYardageStatBlock;
  yardsAllowed: number;
  /** Opposing QB's Full PPR fantasy points for this game, verbatim from nflverse. QB/passing-only and additive -- see {@link NflYardagePlayerHistoryGame.fantasyPointsPpr}. */
  fantasyPointsPpr?: number | null;
  gameScore: NflYardageHistoryGameScore;
  vegasLine: number | null;
};

export type NflYardageOpponentHistory = {
  team: string;
  market: NflProjectionMarket;
  position: string;
  games: NflYardageOpponentHistoryGame[];
};

/**
 * This week's not-yet-played matchup rank, keyed by canonical team abbr
 * (`row.team` / `row.opponent` convention). Computed by
 * `buildPregameRollingEpaAt` in `scripts/lib/nfl-epa-week-rank-core.mjs` --
 * the exact same pregame trailing-10-game EPA/play formula and
 * `rankTeamsAt` ranking function as the historical `oppDefRank` /
 * `oppOffRank` fields above, evaluated at this week's (season, week)
 * cutoff instead of a played game. Apples-to-apples with those historical
 * fields; NOT the same value as `opponentContext.epaEdge` (an 8-game blend
 * from the frozen Season/Last-5 matchup-epa.json artifact) used elsewhere
 * in the review panel.
 */
export type NflYardageCurrentWeekEpaRank = {
  defenseRank: number | null;
  /** Teams with a resolvable pregame rank at this week's cutoff -- not always 32; null whenever defenseRank is null. */
  defenseRankPoolSize: number | null;
  offenseRank: number | null;
  /** Teams with a resolvable pregame rank at this week's cutoff -- not always 32; null whenever offenseRank is null. */
  offenseRankPoolSize: number | null;
};

export type NflYardageHistoryArtifact = {
  _meta: { generatedAt: string; source: string; season: number | null; week: number | null; notes: string[] };
  schemaVersion: string;
  season: number;
  week: number;
  players: Record<string, NflYardagePlayerHistory>;
  teamDefense: Record<string, NflYardageOpponentHistory>;
  /** Keyed by canonical team abbr -- see {@link NflYardageCurrentWeekEpaRank}. */
  currentWeekEpaRanks: Record<string, NflYardageCurrentWeekEpaRank>;
  /** Additive v2 context. Legacy logs retain their original cohort semantics. */
  individualContext?: IndividualYardageHistoryContext;
};

export function playerHistoryKey(playerId: string, market: NflProjectionMarket): string {
  return `${playerId}:${market}`;
}

export function opponentHistoryKey(opponentAbbr: string, market: NflProjectionMarket, position: string): string {
  return `${opponentAbbr}:${market}:${position}`;
}
