import { useEffect, useState } from "react";
import type { NflYardageHistoryArtifact } from "@/lib/nfl/props/types/yardageHistory";

type State = {
  loading: boolean;
  error: string | null;
  data: NflYardageHistoryArtifact | null;
};

const IDLE_STATE: State = { loading: false, error: null, data: null };

/**
 * Loads `public/data/nfl/{season}/yardage-history.json` (the Last-10 player
 * and opponent-defense game logs), generated by
 * `scripts/generate-nfl-yardage-history.mjs`. Fetched lazily -- `enabled`
 * should stay `false` until a user actually expands a player row, so the
 * ~500-player artifact is never pulled down for a page view that never
 * opens the detail panel. A failure here never blocks the base review page
 * -- Show the Work still renders from the already-loaded projection/market/
 * opponent-context data; only the Last-10 tables show an unavailable state.
 */
export function useNflYardageHistory(season: number, enabled: boolean): State {
  const [state, setState] = useState<State>(IDLE_STATE);

  useEffect(() => {
    if (!enabled) return;
    let cancelled = false;
    setState((current) => (current.data || current.loading ? current : { loading: true, error: null, data: null }));

    fetch(`/data/nfl/${season}/yardage-history.json`, { cache: "force-cache" })
      .then(async (response) => {
        if (!response.ok) throw new Error(`Yardage history unavailable (${response.status}).`);
        const json = (await response.json()) as NflYardageHistoryArtifact;
        if (!json || !json.players || !json.teamDefense) throw new Error("Yardage history artifact is malformed.");
        if (!cancelled) setState({ loading: false, error: null, data: json });
      })
      .catch((err: unknown) => {
        const message = err instanceof Error ? err.message : "Yardage history failed to load.";
        if (!cancelled) setState({ loading: false, error: message, data: null });
      });

    return () => {
      cancelled = true;
    };
  }, [season, enabled]);

  return state;
}
