import { existsSync, readFileSync } from 'node:fs';
import path from 'node:path';
export const WIDTH=1080,HEIGHT=1350;
export const COLORS=Object.freeze({navy:'#06111f',panel:'#081725',line:'#34506a',gold:'#f2b134',white:'#f7f4ec',muted:'#a8b4c4',orange:'#f05a24',blue:'#1789e8',purple:'#8b3fc7',green:'#72d13d'});
export const DISPLAY_FONT="'Arial Narrow','Roboto Condensed',Arial,sans-serif",DATA_FONT="Inter,Arial,'Helvetica Neue',sans-serif";
export function esc(v){return String(v??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&apos;');}
export function text(x,y,value,{size=24,weight=700,fill=COLORS.white,anchor='start',family=DATA_FONT,spacing=0}={}){return `<text x="${x}" y="${y}" font-family="${family}" font-size="${size}" font-weight="${weight}" fill="${fill}" text-anchor="${anchor}"${spacing?` letter-spacing="${spacing}"`:''}>${esc(value)}</text>`;}
export function rect(x,y,w,h,{fill='none',stroke='none',sw=0,rx=0,opacity=1}={}){return `<rect x="${x}" y="${y}" width="${w}" height="${h}" rx="${rx}" fill="${fill}" stroke="${stroke}" stroke-width="${sw}" opacity="${opacity}"/>`;}
export function truncate(value,max){const s=String(value??'').trim();return s.length<=max?s:`${s.slice(0,Math.max(1,max-1)).trimEnd()}…`;}
export function finite(value){if(value===null||value===undefined||value==='')return null;const n=Number(value);return Number.isFinite(n)?n:null;}
export function opponentText(row){const opp=String(row?.opponent??'').trim().toUpperCase()||'TBD';return `${row?.venueSide==='away'?'at':'vs'} ${opp}`;}
export function formatOdds(value){const n=finite(value);if(n===null)return null;return n>0?`+${Math.round(n)}`:`${Math.round(n)}`;}
export function formatEdge(value,unit){const n=finite(value);if(n===null)return null;const prefix=n>0?'+':'';return unit==='percent'?`${prefix}${n.toFixed(1)}%`:`${prefix}${n.toFixed(1)}`;}
export function formatLine(side,line){const n=finite(line);if(n===null)return null;const s=String(side??'').toLowerCase();if(!['over','under'].includes(s))return null;return `${s==='over'?'O':'U'} ${n.toFixed(1)}`;}
const ALIASES={AZ:'ARI',CWS:'CHW',CHW:'CHW',KC:'KCR',KCR:'KCR',SD:'SDP',SDP:'SDP',SF:'SFG',SFG:'SFG',TB:'TBR',TBR:'TBR',OAK:'ATH',ATH:'ATH'};
export function normalizeTeam(team){const k=String(team??'').trim().toUpperCase();return ALIASES[k]??k;}
export function logoMarkup(team,x,y,{size=34,root=process.cwd()}={}){const key=normalizeTeam(team)||'MLB';const candidates=[path.join(root,'public','assets','mlb','team-logos',`${key}.svg`),path.join(root,'public','logos','mlb',`${key.toLowerCase()}.svg`)];const found=candidates.find(existsSync);if(found){const raw=readFileSync(found,'utf8').replace(/<\?xml[^>]*>/g,'').replace(/<!DOCTYPE[^>]*>/g,'');const encoded=`data:image/svg+xml;base64,${Buffer.from(raw).toString('base64')}`;return `<image href="${encoded}" x="${x}" y="${y}" width="${size}" height="${size}" preserveAspectRatio="xMidYMid meet"/>`;}return `${rect(x,y,size,size,{fill:'#172b3f',stroke:'#6b7f92',sw:1.5,rx:size/2})}${text(x+size/2,y+size*.66,truncate(key,3),{size:12,weight:800,anchor:'middle'})}`;}
export function svgShell(body){return `<svg xmlns="http://www.w3.org/2000/svg" width="${WIDTH}" height="${HEIGHT}" viewBox="0 0 ${WIDTH} ${HEIGHT}"><defs><linearGradient id="bg" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="#020812"/><stop offset="1" stop-color="#071a2d"/></linearGradient><filter id="glow"><feGaussianBlur stdDeviation="5" result="b"/><feMerge><feMergeNode in="b"/><feMergeNode in="SourceGraphic"/></feMerge></filter></defs>${body}</svg>`;}
export function renderBackground(){return `${rect(0,0,WIDTH,HEIGHT,{fill:'url(#bg)'})}<path d="M0 150 Q540 40 1080 150" fill="none" stroke="#17334d" stroke-width="2" opacity=".7"/><g opacity=".85" filter="url(#glow)"><circle cx="65" cy="55" r="10" fill="#fff"/><circle cx="92" cy="45" r="9" fill="#fff"/><circle cx="1015" cy="55" r="10" fill="#fff"/><circle cx="988" cy="45" r="9" fill="#fff"/></g>`;}
export function panel(x,y,w,h,color,title){return `${rect(x,y,w,h,{fill:COLORS.panel,stroke:color,sw:2,rx:12})}${rect(x,y,w,50,{fill:color,rx:12})}${rect(x,y+38,w,12,{fill:color})}${text(x+24,y+36,title,{size:31,weight:900,family:DISPLAY_FONT,spacing:.4})}`;}
export function header({edition,slateDate,updatedTimeEt}){const confirmed=edition==='confirmed';return `${text(540,78,'JOE KNOWS BALL',{size:52,weight:900,fill:COLORS.gold,anchor:'middle',family:DISPLAY_FONT,spacing:1.4})}${text(540,155,'MLB DAILY MODEL CARD',{size:57,weight:900,anchor:'middle',family:DISPLAY_FONT,spacing:1.2})}${rect(78,183,350,48,{fill:'#08131f',stroke:confirmed?COLORS.green:COLORS.gold,sw:2,rx:12})}${text(253,216,confirmed?'✓  CONFIRMED UPDATE':'MORNING MODEL  ☀',{size:25,weight:900,fill:confirmed?COLORS.green:COLORS.gold,anchor:'middle',family:DISPLAY_FONT})}${text(540,215,slateDate,{size:23,weight:800,anchor:'middle'})}${text(985,215,`◷  UPDATED ${updatedTimeEt}`,{size:21,weight:800,anchor:'end'})}`;}
export function footer(statusNote,confirmed){return `${rect(22,1240,1036,58,{fill:'#06111f',stroke:confirmed?COLORS.green:COLORS.gold,sw:2,rx:12})}${text(540,1278,`${confirmed?'✓':'!'}  ${statusNote}`,{size:22,weight:800,fill:confirmed?COLORS.green:COLORS.gold,anchor:'middle'})}${text(185,1332,'◉  joeknowsball.com',{size:20,weight:600,anchor:'middle'})}${text(820,1332,'𝕏  @_joeknowsball_',{size:20,weight:600,anchor:'middle'})}`;}
