import { finite, formatEdge, formatLine, formatOdds, truncate } from './core.mjs';
export const MORNING_STATUS='Lineups not confirmed. Odds may not yet be available.';
export const CONFIRMED_STATUS='Updated with confirmed lineups, starters, and available markets.';
export const DEFAULT_READINESS={minHomeRunRows:4,minStrikeoutRows:3,minValueRows:2,preferredHomeRunRows:6,preferredStrikeoutRows:5,preferredValueRows:4};
function base(input,edition){if(input?.edition!==edition)throw new Error(`Expected edition ${edition}`);if(input?.schemaVersion!==1)throw new Error('schemaVersion must be 1');if(!/^\d{4}-\d{2}-\d{2}$/.test(String(input.slateDate??'')))throw new Error('slateDate must be YYYY-MM-DD');return {...input,homeRuns:Array.isArray(input.homeRuns)?input.homeRuns:[],strikeouts:Array.isArray(input.strikeouts)?input.strikeouts:[],links:{website:'joeknowsball.com',xHandle:'@_joeknowsball_',...(input.links??{})}};}
export function normalizeMorning(input){const x=base(input,'morning');return {...x,preview:Boolean(input.preview),publishReady:true,statusNote:MORNING_STATUS,homeRuns:x.homeRuns.slice(0,6).map((r,i)=>({rank:r.rank??i+1,player:truncate(r.player,24),team:r.team,opponent:r.opponent,venueSide:r.venueSide,hrScore:finite(r.hrScore)})),strikeouts:x.strikeouts.slice(0,5).map((r,i)=>({rank:r.rank??i+1,pitcher:truncate(r.pitcher,24),team:r.team,opponent:r.opponent,venueSide:r.venueSide,kScore:finite(r.kScore??r.strikeoutScore),projectedK:finite(r.projectedK??r.projectedKs)})),snapshot:{gamesModeled:finite(x.snapshot?.gamesModeled),projectedStartingPitchers:finite(x.snapshot?.projectedStartingPitchers),modeledHitters:finite(x.snapshot?.modeledHitters??x.snapshot?.projectedBatters),highestHrScore:x.snapshot?.highestHrScore??null,highestProjectedK:x.snapshot?.highestProjectedK??null,lastRefresh:x.snapshot?.lastRefresh??x.updatedTimeEt??'—'},readiness:{ready:true,reasons:[],counts:{homeRuns:Math.min(x.homeRuns.length,6),strikeouts:Math.min(x.strikeouts.length,5)}}};}
export function evaluateConfirmedReadiness(data,thresholds=DEFAULT_READINESS,{valuesSourceAvailable=true}={}){const reasons=[];const counts={homeRuns:data.homeRuns.length,strikeouts:data.strikeouts.length,values:Array.isArray(data.values)?data.values.length:0};if(!valuesSourceAvailable)reasons.push('CONFIRMED_VALUES_SOURCE_UNAVAILABLE');if(counts.homeRuns<thresholds.minHomeRunRows)reasons.push('INSUFFICIENT_CONFIRMED_HR_ROWS');if(counts.strikeouts<thresholds.minStrikeoutRows)reasons.push('INSUFFICIENT_CONFIRMED_K_ROWS');if(counts.values<thresholds.minValueRows)reasons.push('INSUFFICIENT_CONFIRMED_VALUE_ROWS');return {ready:reasons.length===0,reasons,counts};}
export function normalizeConfirmed(input,{preview=false,thresholds=DEFAULT_READINESS,valuesSourceAvailable=true}={}){const x=base(input,'confirmed');const readiness=evaluateConfirmedReadiness(x,thresholds,{valuesSourceAvailable});if(!readiness.ready&&!preview){const e=new Error(`Confirmed card not ready: ${readiness.reasons.join(', ')}`);e.readiness=readiness;throw e;}const homeRuns=x.homeRuns.slice(0,6).map((r,i)=>{const odds=formatOdds(r.odds);if(!odds)throw new Error(`Confirmed HR row ${i+1} requires odds`);return {rank:r.rank??i+1,player:truncate(r.player,24),team:r.team,opponent:r.opponent,venueSide:r.venueSide,hrScore:finite(r.hrScore),odds};});const strikeouts=x.strikeouts.slice(0,5).map((r,i)=>{const line=formatLine(r.side,r.line),odds=formatOdds(r.odds),edge=formatEdge(r.edge,r.edgeUnit);if(!line||!odds||!edge)throw new Error(`Confirmed K row ${i+1} requires side, line, odds and edge`);return {rank:r.rank??i+1,pitcher:truncate(r.pitcher,24),team:r.team,opponent:r.opponent,venueSide:r.venueSide,kScore:finite(r.kScore??r.strikeoutScore),line,odds,edge};});const values=(x.values??[]).slice(0,4).map((r,i)=>{const odds=formatOdds(r.odds),edge=formatEdge(r.edge,r.edgeUnit);if(!r.player||!r.market||!odds||!edge)throw new Error(`Confirmed value row ${i+1} is incomplete`);return {rank:r.rank??i+1,player:truncate(r.player,22),team:r.team,market:truncate(r.market,18),line:r.side?formatLine(r.side,r.line):(finite(r.line)?.toFixed(1)??'—'),odds,edge};});return {...x,preview:Boolean(preview),publishReady:readiness.ready&&!preview,statusNote:CONFIRMED_STATUS,homeRuns,strikeouts,values,readiness};}
export function deriveMorningSnapshot({gamesModeled,projectedStartingPitchers,modeledHitters,homeRuns=[],strikeouts=[],lastRefresh}){const hr=homeRuns.reduce((a,b)=>(finite(b.hrScore)??-Infinity)>(finite(a?.hrScore)??-Infinity)?b:a,null);const k=strikeouts.reduce((a,b)=>(finite(b.projectedK??b.projectedKs)??-Infinity)>(finite(a?.projectedK??a?.projectedKs)??-Infinity)?b:a,null);return {gamesModeled,projectedStartingPitchers,modeledHitters,highestHrScore:hr?{value:finite(hr.hrScore),player:hr.player}:null,highestProjectedK:k?{value:finite(k.projectedK??k.projectedKs),player:k.pitcher}:null,lastRefresh};}
