import generated2026 from "../../../../data/generated/cfb/2026-season-stats-v1.json";
import generated2025 from "../../../../data/generated/cfb/2025-season-stats-v1.json";
import type { CfbSeasonStats } from "../types";
import { CFB_FBS_TEAM_COUNT, CFB_TEAM_METADATA } from "../teamMetadata";
import type { CfbSeasonStatsArtifact } from "../../../lib/cfb/seasonStats/buildSeasonStatsArtifact";
import type { CfbRankedStatMetric } from "../../../lib/cfb/seasonStats/rankSeasonStats";

/**
 * CFBD-derived season stats, generated by `npm run cfb:build-season-stats`
 * from the raw /games + /games/teams caches (see
 * src/lib/cfb/seasonStats/buildSeasonStatsArtifact.ts for formulas/policy).
 * Do not hand-edit the underlying artifact.
 *
 * In preseason (0 completed 2026 games) every team's stats are honestly
 * null with gamesPlayed: 0 — this file NEVER substitutes 2025 values into
 * the 2026 dataset. CFB_STATS_PREVIOUS_SEASON_BY_TEAM below carries 2025 as
 * a separately-named, explicitly-labeled dataset for future "Last Season"
 * UI use; it is not merged into CfbTeam.stats.
 */

function emptyStats(teamId: string): CfbSeasonStats {
  return {
    teamId,
    gamesPlayed: 0,
    pointsPerGame: null,
    yardsPerPlay: null,
    pointsPerPlay: null,
    rushYardsPerGame: null,
    yardsPerRush: null,
    passYardsPerGame: null,
    yardsPerPass: null,
    thirdDownPct: null,
    completionPct: null,
    turnovers: null,
    pointsAllowedPerGame: null,
    yardsPerPlayAllowed: null,
    opponentPointsPerPlay: null,
    rushYardsAllowedPerGame: null,
    yardsPerRushAllowed: null,
    passYardsAllowedPerGame: null,
    yardsPerPassAllowed: null,
    opponentThirdDownPct: null,
    opponentCompletionPct: null,
    takeaways: null,
  };
}

/**
 * Validates a generated artifact's shape defensively — this runs in the
 * browser bundle, so a malformed/short artifact must degrade to the honest
 * all-null placeholder rather than crash the app or silently drop teams.
 */
function loadArtifact(raw: unknown, label: string): CfbSeasonStatsArtifact | null {
  const artifact = raw as CfbSeasonStatsArtifact;
  if (
    !artifact ||
    artifact.schemaVersion !== "jkb-cfb-season-stats-v1" ||
    !Array.isArray(artifact.teams) ||
    artifact.teams.length !== CFB_FBS_TEAM_COUNT
  ) {
    console.error(
      `[cfb season stats] ${label} artifact failed shape validation (expected ${CFB_FBS_TEAM_COUNT} teams) — falling back to null stats.`,
    );
    return null;
  }
  return artifact;
}

const ARTIFACT_2026 = loadArtifact(generated2026, "2026-season-stats-v1");
const ARTIFACT_2025 = loadArtifact(generated2025, "2025-season-stats-v1");

function statsByTeamFromArtifact(artifact: CfbSeasonStatsArtifact | null): Record<string, CfbSeasonStats> {
  const byTeam = new Map(artifact?.teams.map((row) => [row.teamId, row.stats]) ?? []);
  return Object.fromEntries(
    CFB_TEAM_METADATA.map((team) => [team.id, byTeam.get(team.id) ?? emptyStats(team.id)]),
  );
}

/** True once the 2026 artifact reflects at least one completed game. */
export const CFB_STATS_2026_HAS_DATA: boolean = (ARTIFACT_2026?.gamesPlayed ?? 0) > 0;

export const CFB_STATS_2026_GENERATED_AT: string | null = ARTIFACT_2026?.generatedAt ?? null;

export const CFB_STATS_BY_TEAM: Record<string, CfbSeasonStats> = statsByTeamFromArtifact(ARTIFACT_2026);

export const CFB_STATS_2026: CfbSeasonStats[] = CFB_TEAM_METADATA.map(
  (team) => CFB_STATS_BY_TEAM[team.id],
);

function ranksByTeamFromArtifact(
  artifact: CfbSeasonStatsArtifact | null,
): Record<string, Partial<Record<CfbRankedStatMetric, number>>> {
  const byTeam = new Map(artifact?.teams.map((row) => [row.teamId, row.ranks]) ?? []);
  return Object.fromEntries(CFB_TEAM_METADATA.map((team) => [team.id, byTeam.get(team.id) ?? {}]));
}

/** Per-team, per-metric national rank (competition ranking) for the 2026 artifact. */
export const CFB_STATS_RANKS_BY_TEAM: Record<string, Partial<Record<CfbRankedStatMetric, number>>> =
  ranksByTeamFromArtifact(ARTIFACT_2026);

/**
 * 2025 ("Last Season") stats — a SEPARATE dataset from CFB_STATS_BY_TEAM.
 * Not read by CfbTeam.stats/composeTeam; kept available for a future unit
 * to render as an explicitly-labeled "Last Season" comparison while 2026
 * has no completed games yet. Never presented as current-season data.
 */
export const CFB_STATS_PREVIOUS_SEASON_BY_TEAM: Record<string, CfbSeasonStats> =
  statsByTeamFromArtifact(ARTIFACT_2025);

export const CFB_STATS_PREVIOUS_SEASON_YEAR: number | null = ARTIFACT_2025?.season ?? null;

/** Per-team, per-metric national rank for the 2025 ("Last Season") artifact. */
export const CFB_STATS_PREVIOUS_SEASON_RANKS_BY_TEAM: Record<
  string,
  Partial<Record<CfbRankedStatMetric, number>>
> = ranksByTeamFromArtifact(ARTIFACT_2025);
