/**
 * Canonical universal current-season 2026 NFL OVR / OFF / DEF ratings.
 *
 * Directly blends each team's preseason anchor with the live Team
 * Performance Rating (src/lib/nfl/performanceComposite2026.ts, generated by
 * scripts/generate-nfl-team-performance-analytics.mts), using the same
 * completed-games weight table for all three:
 *
 *   rating = preseasonWeight * preseasonRating + performanceWeight * performanceRating
 *
 * Anchors:
 *   OVR  preseason = nfl-power-v0.4-beta rating2026 (immutable projection)
 *        live       = performance.performanceRating
 *   OFF  preseason = the existing public preseason v0.3.1 offenseRating
 *        live       = performance.offenseRating
 *   DEF  preseason = the existing public preseason v0.3.1 defenseRating
 *        live       = performance.defenseRating
 *
 * The weight table ramps by that team's OWN completed-game count (never a
 * league-wide week number, so bye weeks fall out naturally):
 *   0 games: 100% preseason /   0% performance
 *   1 game:   80% preseason /  20% performance
 *   2 games:  60% preseason /  40% performance
 *   3 games:  40% preseason /  60% performance
 *   4 games:  25% preseason /  75% performance
 *   5 games:  10% preseason /  90% performance
 *   6+ games:  0% preseason / 100% performance
 *
 * This REPLACES the old v0.3.1-delta live-rating methodology entirely
 * (`preseasonV04 + evidenceWeight * (currentV03 − preseasonV03)`) as the
 * live-rating calculation. The v0.3.1 artifacts and model code are untouched
 * everywhere else in the app (historical review, SOS, spread models, the
 * Guide) — only their former role of supplying the CURRENT in-season OVR
 * number is retired here. There is no parallel or hidden fallback to that
 * old methodology: when live performance data is required and unavailable,
 * this module throws rather than silently substituting it (or the league
 * average, or zero).
 *
 * Ranks for OVR/OFF/DEF are computed independently, each AFTER its own
 * blend — an ordinal rank is never blended, and preseason ranks are never
 * reused for the live board.
 *
 * This module is framework-free and never fetches: it takes already-loaded,
 * already-validated v0.3.1/v0.4/Performance-Analytics artifacts and returns
 * a plain board. src/hooks/useNflCurrentRating2026.ts is the only place that
 * performs I/O, composing the existing useNflV03Artifacts / useNflV04Projection
 * / useNflTeamPerformanceAnalytics loaders so validation logic is never
 * duplicated here.
 *
 * Every anchor is a required input for a team once its games-played count
 * calls for it (see FALLBACK POLICY below) — a team present in the v0.4
 * board must have a matching preseason v0.3.1 row and, once its own
 * completed-game count is > 0, a matching, fully-populated Performance
 * Analytics row. Missing required data throws rather than silently treating
 * it as "no performance yet".
 *
 * FALLBACK POLICY (strict, no silent substitution):
 *   0 games            -> preseason exactly (performanceWeight is 0, so a
 *                          null/absent performance row for this team is
 *                          expected and fine).
 *   1-5 / 6+ games      -> that team's performance row MUST have finite
 *                          performanceRating/offenseRating/defenseRating, or
 *                          building the board throws. There is no partial
 *                          blend with a missing performance number, and the
 *                          old v0.3.1 delta model is never used as a
 *                          hidden fallback for a team that has played games.
 *
 * SOS never enters this module. This board carries no schedule field of any
 * kind, by design, so it cannot be threaded back into the rating.
 */

import { rankByDescending } from "@/lib/nfl/publicPowerRatings";
import type { NflPublicProjectionBoard } from "@/lib/nfl/publicProjection2026";
import type { NflV03PreseasonArtifact } from "@/lib/nfl/v03Review";
import type { TeamPerformanceAnalyticsArtifact } from "@/lib/nfl/teamPerformanceAnalytics";

/** 6 stands for "6 or more" — the ramp is capped, not open-ended. */
export type EvidenceGameCount = 0 | 1 | 2 | 3 | 4 | 5 | 6;

export type CurrentRatingWeights = { preseasonWeight: number; performanceWeight: number };

/** The approved direct-blend weight table, identical for OVR/OFF/DEF. */
export const CURRENT_RATING_WEIGHTS_BY_GAMES: Readonly<Record<EvidenceGameCount, CurrentRatingWeights>> = Object.freeze({
  0: Object.freeze({ preseasonWeight: 1.00, performanceWeight: 0.00 }),
  1: Object.freeze({ preseasonWeight: 0.80, performanceWeight: 0.20 }),
  2: Object.freeze({ preseasonWeight: 0.60, performanceWeight: 0.40 }),
  3: Object.freeze({ preseasonWeight: 0.40, performanceWeight: 0.60 }),
  4: Object.freeze({ preseasonWeight: 0.25, performanceWeight: 0.75 }),
  5: Object.freeze({ preseasonWeight: 0.10, performanceWeight: 0.90 }),
  6: Object.freeze({ preseasonWeight: 0.00, performanceWeight: 1.00 }),
});

export const CURRENT_RATING_SCALE = Object.freeze({ min: 1, max: 99 });

/**
 * Team-specific blend weights from that team's own completed-game count.
 * Never a global week number. Negative/non-finite input is treated as 0
 * games; fractional input is floored (a partially-recorded game is not a
 * completed game); anything at or above 6 caps at the 6+ weights.
 */
export function currentRatingWeightsFor(gamesPlayed: number): CurrentRatingWeights {
  if (!Number.isFinite(gamesPlayed) || gamesPlayed <= 0) return CURRENT_RATING_WEIGHTS_BY_GAMES[0];
  const normalized = Math.min(6, Math.floor(gamesPlayed)) as EvidenceGameCount;
  return CURRENT_RATING_WEIGHTS_BY_GAMES[normalized];
}

export function clampRating(value: number): number {
  return Math.max(CURRENT_RATING_SCALE.min, Math.min(CURRENT_RATING_SCALE.max, value));
}

/**
 * The one place any of OVR/OFF/DEF's blend formula is evaluated — a single
 * shared helper so the three ratings can never silently diverge in method.
 * Direct weighted blend, NOT a delta from a baseline:
 *   rating = weights.preseasonWeight * preseasonValue + weights.performanceWeight * performanceValue
 */
export function blendCurrentRating(
  preseasonValue: number,
  performanceValue: number,
  weights: CurrentRatingWeights
): number {
  const blended = weights.preseasonWeight * preseasonValue + weights.performanceWeight * performanceValue;
  return clampRating(blended);
}

export type CurrentRatingTeamState = "preseason" | "live";

export type CurrentRatingRow = {
  abbr: string;
  team: string;
  division: string;
  /** Clamped [1, 99] universal current OVR — the blend of v0.4 preseason and live performanceRating. */
  rating: number;
  /** 1..32, descending by `rating`, deterministic ties (see rankByDescending). Computed AFTER blending. */
  rank: number;
  /** Clamped [1, 99] universal current OFF — the blend of preseason v0.3.1 offenseRating and live performance.offenseRating. */
  offenseRating: number;
  /** 1..32, descending by `offenseRating`, computed AFTER blending. */
  offenseRank: number;
  /** Clamped [1, 99] universal current DEF — the blend of preseason v0.3.1 defenseRating and live performance.defenseRating. */
  defenseRating: number;
  /** 1..32, descending by `defenseRating`, computed AFTER blending. */
  defenseRank: number;
  /** Raw (unblended) full-season Team Performance Rating composite, for provenance — null until this team has completed games. */
  performanceRating: number | null;
  /** Raw (unblended) Performance Rating league rank, for provenance — null until this team has completed games. */
  performanceRank: number | null;
  /** This team's own completed-game count, from the Performance Analytics artifact. */
  gamesPlayed: number;
  preseasonWeight: number;
  performanceWeight: number;
  /** "live" once this team has any completed games (performanceWeight > 0); "preseason" otherwise. */
  state: CurrentRatingTeamState;
  preseasonV04Rating: number;
  preseasonOffenseRating: number;
  preseasonDefenseRating: number;
};

export type CurrentRatingBoardState = "preseason" | "live";

export type CurrentRatingBoard = {
  season: number;
  /** "live" once AT LEAST ONE team has completed games; per-team state can still be "preseason". */
  state: CurrentRatingBoardState;
  teams: CurrentRatingRow[];
};

export type BuildCurrentRatingBoardInput = {
  season: number;
  /** Required anchor. Must already be validated (see v04Projection.ts). */
  v04Board: NflPublicProjectionBoard;
  /** Required anchor: the immutable preseason v0.3.1 baseline (OFF/DEF preseason anchors live here too). */
  preseasonV03: NflV03PreseasonArtifact;
  /** Required once any team has completed games; may be the honest zero-game artifact before the season starts. Must already be validated. */
  performanceAnalytics: TeamPerformanceAnalyticsArtifact;
};

function requireFiniteRating(value: number | null, label: string): number {
  if (value === null || !Number.isFinite(value)) {
    throw new Error(`currentRating2026: ${label} is required once games have been played, but is missing/invalid`);
  }
  return value;
}

/**
 * Build the universal current OVR/OFF/DEF board from already-validated
 * artifacts. Throws (never silently substitutes) when:
 *  - a v0.4 team has no matching preseason v0.3.1 row
 *  - a v0.4 team has no matching Performance Analytics row at all
 *  - a team's own completed-game count is > 0 but its Performance Analytics
 *    performanceRating/offenseRating/defenseRating are not all finite
 */
export function buildCurrentRatingBoard(input: BuildCurrentRatingBoardInput): CurrentRatingBoard {
  const { season, v04Board, preseasonV03, performanceAnalytics } = input;

  const preseasonV03ByAbbr = new Map(preseasonV03.ratings.map((row) => [row.abbr, row]));
  const performanceByAbbr = new Map(performanceAnalytics.teams.map((row) => [row.team, row]));

  const unranked = v04Board.teams.map((v04team) => {
    const preseasonRow = preseasonV03ByAbbr.get(v04team.abbr);
    if (!preseasonRow) {
      throw new Error(`currentRating2026: missing required preseason v0.3.1 baseline for ${v04team.abbr}`);
    }
    const performanceRow = performanceByAbbr.get(v04team.abbr);
    if (!performanceRow) {
      throw new Error(`currentRating2026: missing required Performance Analytics row for ${v04team.abbr}`);
    }

    const gamesPlayed = Math.max(0, Math.floor(performanceRow.gamesPlayed));
    const weights = currentRatingWeightsFor(gamesPlayed);

    const performanceRating = weights.performanceWeight > 0
      ? requireFiniteRating(performanceRow.performance.performanceRating, `${v04team.abbr} performance.performanceRating`)
      : null;
    const performanceOffense = weights.performanceWeight > 0
      ? requireFiniteRating(performanceRow.performance.offenseRating, `${v04team.abbr} performance.offenseRating`)
      : null;
    const performanceDefense = weights.performanceWeight > 0
      ? requireFiniteRating(performanceRow.performance.defenseRating, `${v04team.abbr} performance.defenseRating`)
      : null;

    const rating = weights.performanceWeight > 0
      ? blendCurrentRating(v04team.rating2026, performanceRating as number, weights)
      : clampRating(v04team.rating2026);
    const offenseRating = weights.performanceWeight > 0
      ? blendCurrentRating(preseasonRow.offenseRating, performanceOffense as number, weights)
      : clampRating(preseasonRow.offenseRating);
    const defenseRating = weights.performanceWeight > 0
      ? blendCurrentRating(preseasonRow.defenseRating, performanceDefense as number, weights)
      : clampRating(preseasonRow.defenseRating);

    const row: Omit<CurrentRatingRow, "rank" | "offenseRank" | "defenseRank"> = {
      abbr: v04team.abbr,
      team: v04team.team,
      division: v04team.division,
      rating,
      offenseRating,
      defenseRating,
      performanceRating: performanceRow.performance.performanceRating,
      performanceRank: performanceRow.performance.performanceRank,
      gamesPlayed,
      preseasonWeight: weights.preseasonWeight,
      performanceWeight: weights.performanceWeight,
      state: weights.performanceWeight > 0 ? "live" : "preseason",
      preseasonV04Rating: v04team.rating2026,
      preseasonOffenseRating: preseasonRow.offenseRating,
      preseasonDefenseRating: preseasonRow.defenseRating,
    };
    return row;
  });

  function rank(pick: (row: (typeof unranked)[number]) => number): Map<string, number> {
    return rankByDescending(unranked.map((row) => ({ key: row.abbr, value: pick(row), name: row.team, teamId: row.abbr })));
  }
  const ovrRanks = rank((row) => row.rating);
  const offRanks = rank((row) => row.offenseRating);
  const defRanks = rank((row) => row.defenseRating);

  const teams: CurrentRatingRow[] = unranked
    .map((row) => ({
      ...row,
      rank: ovrRanks.get(row.abbr) ?? unranked.length,
      offenseRank: offRanks.get(row.abbr) ?? unranked.length,
      defenseRank: defRanks.get(row.abbr) ?? unranked.length,
    }))
    .sort((a, b) => a.rank - b.rank);

  const boardState: CurrentRatingBoardState = teams.some((row) => row.gamesPlayed > 0) ? "live" : "preseason";

  return { season, state: boardState, teams };
}
