import { describe, it, expect } from "vitest";
import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import { JKB_POWER_NUMBER_MODEL_VERSION, OVR_TO_POINTS_COEFFICIENT, HOME_FIELD_ADVANTAGE_POINTS } from "@/lib/nfl/jkbPowerNumber2026";

/**
 * Invariants of the PRODUCTION public/data/nfl/matchup-projections.json
 * artifact, generated by scripts/generate-nfl-matchup-projections.mts from
 * the canonical Current OVR board (jkb-power-number-v1.0.0, 2026-08-19).
 *
 * This replaces the old nfl-spread-v0.1.0 "published artifact" suite that
 * used to live in spreadModel.test.ts — that model no longer generates this
 * file (see scripts/analysis/nfl-spread-v0.1.0-legacy/ for its own tests).
 */

const artifact = JSON.parse(
  readFileSync(resolve(process.cwd(), "public/data/nfl/matchup-projections.json"), "utf-8")
);

describe("jkb-power-number-v1.0.0 published artifact", () => {
  it("carries the approved model version and configuration", () => {
    expect(artifact.modelVersion).toBe(JKB_POWER_NUMBER_MODEL_VERSION);
    expect(artifact.model.ovrToPointsCoefficient).toBe(OVR_TO_POINTS_COEFFICIENT);
    expect(artifact.model.homeFieldAdvantage).toBe(HOME_FIELD_ADVANTAGE_POINTS);
    expect(artifact.model.neutralSiteHomeFieldAdvantage).toBe(0);
    expect(artifact.model.strengthInput).toMatch(/currentRating2026/);
    // No fitted parameters at all -- unlike the retired model, nothing here
    // is fit to this season's data; beta and HFA are both fixed constants
    // carried over from the approved calibration.
    expect(artifact.model.fittedParameters).toEqual([]);
    expect(artifact.model.marketInputUsed).toBe(false);
  });

  it("projects a full 2026 regular season with a finite margin for every game", () => {
    const games = Object.values(artifact.projections) as Array<Record<string, unknown>>;
    expect(games.length).toBeGreaterThan(0);
    for (const g of games) {
      expect(Number.isFinite(g.projectedHomeMargin as number)).toBe(true);
      expect(Number.isFinite(g.homeCurrentOVR as number)).toBe(true);
      expect(Number.isFinite(g.awayCurrentOVR as number)).toBe(true);
      expect(typeof g.formattedJkbSpread).toBe("string");
    }
  });

  it("computes every Power Number as (OVR - leagueAverageOVR) x 0.24, exactly", () => {
    for (const g of Object.values(artifact.projections) as Array<Record<string, number>>) {
      const expectedHome = (g.homeCurrentOVR - g.leagueAverageOVR) * OVR_TO_POINTS_COEFFICIENT;
      const expectedAway = (g.awayCurrentOVR - g.leagueAverageOVR) * OVR_TO_POINTS_COEFFICIENT;
      expect(g.homePowerNumber).toBeCloseTo(expectedHome, 8);
      expect(g.awayPowerNumber).toBeCloseTo(expectedAway, 8);
    }
  });

  it("applies home-field advantage correctly by site (2.0 normal, 0.0 neutral)", () => {
    const games = Object.values(artifact.projections) as Array<Record<string, unknown>>;
    const neutralGames = games.filter((g) => g.neutralSite === true);
    const normalGames = games.filter((g) => g.neutralSite === false);
    expect(neutralGames.length).toBeGreaterThan(0);
    expect(normalGames.length).toBeGreaterThan(0);
    for (const g of neutralGames) expect(g.homeFieldAdvantage).toBe(0);
    for (const g of normalGames) expect(g.homeFieldAdvantage).toBe(HOME_FIELD_ADVANTAGE_POINTS);
  });

  it("derives projectedHomeMargin as neutralProjectedMargin + homeFieldAdvantage, exactly", () => {
    for (const g of Object.values(artifact.projections) as Array<Record<string, number>>) {
      expect(g.projectedHomeMargin).toBeCloseTo(g.neutralProjectedMargin + g.homeFieldAdvantage, 8);
    }
  });

  it("keeps sportsbook notation consistent with the sign of the projected margin", () => {
    for (const g of Object.values(artifact.projections) as Array<Record<string, unknown>>) {
      const margin = g.projectedHomeMargin as number;
      const display = g.formattedJkbSpread as string;
      const homeTeam = (g.homeTeam as string).toUpperCase();
      const awayTeam = (g.awayTeam as string).toUpperCase();
      if (Math.round(margin * 10) === 0) {
        expect(display).toBe("PK");
      } else if (margin > 0) {
        expect(display.startsWith(homeTeam)).toBe(true);
      } else {
        expect(display.startsWith(awayTeam)).toBe(true);
      }
    }
  });

  it("never references market/Vegas data anywhere in the artifact", () => {
    const text = JSON.stringify(artifact).toLowerCase();
    for (const term of ["spreadline", "moneyline", "vegas", "sportsbook", "consensus"]) {
      expect(text).not.toContain(term);
    }
  });
});
