// Canonical, shared type + index builder for the Razzball defensive
// slot-vs-wide PPG-allowed artifact (public/data/nfl/{season}/slot-wide-defense-context.json,
// generated by scripts/refresh-nfl-slot-wide-defense-context.mts). Lives
// outside src/lib/nfl/dfs so any future NFL consumer (not just the DFS
// board) can read the same artifact without a DFS-specific import.
//
// These fields describe the OPPOSING DEFENSE's distribution of PPG allowed
// between slot and wide alignments -- never an individual receiver's own
// slot/wide alignment, which is a different data source.

import { normalizeNflTeamAbbr } from "@/lib/nfl/identity/identity";

export type SlotWideDefenseTeamEntry = {
  team: string;
  /** Total fantasy PPG allowed to WRs, all alignments. */
  totalPpgAllowed: number;
  /** Fantasy PPG allowed to receivers lined up in the slot. */
  slotPpgAllowed: number;
  /** Fantasy PPG allowed to receivers lined up wide. */
  widePpgAllowed: number;
  /** Share of receiving production this defense has allowed to the slot, 0-1. */
  slotPct: number;
  /** Share of receiving production this defense has allowed to wide alignments, 0-1. */
  widePct: number;
  nextOpponent: string | null;
};

export type SlotWideDefenseContextArtifact = {
  schemaVersion: "nfl-slot-wide-defense-context-v1";
  source: string;
  sourceUrl: string;
  season: number;
  generatedAt: string;
  teams: readonly SlotWideDefenseTeamEntry[];
};

/** Keyed by normalized team abbreviation. Empty map when the artifact hasn't loaded. */
export function buildSlotWideDefenseIndex(artifact: SlotWideDefenseContextArtifact | null | undefined): ReadonlyMap<string, SlotWideDefenseTeamEntry> {
  const map = new Map<string, SlotWideDefenseTeamEntry>();
  if (!artifact) return map;
  for (const team of artifact.teams) {
    const normalized = normalizeNflTeamAbbr(team.team);
    if (normalized) map.set(normalized, team);
  }
  return map;
}
